### PR TITLE
Found a issue.

### PR DESCRIPTION
**Pull request by AlexFreedomMod**

### CODE REVIEW

**Comment by SlicedCaek** [comment]
Oh Thanks, and also @AlexFreedomMod, do you want to help me make a new Custom made all-Op CFM Remastered

**Comment by AlexFreedomMod** [comment]
Sure i guess. but my netbeans is having TotalFreedom/TotalFreedomMod#600

**Comment by SlicedCaek** [comment]
@AlexFreedomMod you don't have to use Netbeans, I'll compile it with jar but now I am just adding Commands and stuff

**Comment by AlexFreedomMod** [comment]
Ok, so we are adding the basic stuff and then the harder stuff?

**Comment by AlexFreedomMod** [comment]
@SlicedCaek i fixed the issue

**Pull request merged**
